# NOTE: If you require support setting up the plugin, reach out to me via the discord server (which you can find on the Minehut dashboard via the "Your Stuff" tab, and by hitting "Get Support" on the plugin or by visiting https://www.echology.page/socials/discord)

# Useful links:
# - https://x.echology.page/discord [discord invite]
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html [list of valid item types]
# - https://www.spigotmc.org/wiki/itemstack-serialization/ [info on item configuration]

Health:

  # This section is designated to the configuration based around Health values and aspects of the plugin.

  multiplier: # a multiplier for the amount of lives gained or lost
    gain: 1
      # amount to multiply by

    loss: 1
      # amount to multiply by

    # gain multiplier determines the increased amount of hp that the player will receive after getting a kill

    # loss multiplier determines the increased amount of hp that the player will lose after dying

  upper-limit: 100
    # value of the upper health limit

  # the upper health limit is the cap for how much a player's health can increase, setting this will allow a maximum amount of health to be reached.

  lower-limit: 1
    # value of the lower health limit

  # the lower health limit refers to when the player's lives goes below the limit
  # configured in "Out-Of-Lives"

# this section defines values for on death actions
Kills:

  # This section is designated to the configuration of the kill-based aspects of the plugin.

  pvp:

    # this section is used when PvP is the reason for death
    # this section will only be used if a player dies because of another player

    enabled: true
    # determines if lifesteal will run on pvp

    # configure the messages for the victim
    victim: "&6You have been killed by &e%attacker%&6. Lives: &c%victim-lives%"

      #  determines the message sent into chat to the victim


    # configure the messages for the attacker
    attacker: "&6You killed &e%victim%&6. Lives: &c%attacker-lives%"

      # determines the message sent into chat to the attacker

    death-message: "&6%victim% &e[%victim-lives%]&6 was killed by %attacker% &e[%attacker-lives%]"
    # death-message defines the message that sends in chat for all players, disabling this will use the default options for the server.
    # Note: to turn off death messages, use the command "/gamerule showDeathMessages false"

  other:

    # this section is used when the reason for death is not due to a player
    # including mobs, fall damage, etc.

    enabled: false
    # determines if lifesteal will run on other death causes

    # configure the messages for the victim
    victim: "&6You have died. Lives: &c%victim-lives%"

      # chat-message value determines the message sent into chat to the victim

    death-message: "&6%victim% &e[%victim-lives%]&6 died"
    # death-message defines the message that sends in chat for all players, disabling this will use the default options for the server.
    # Note: to turn off death messages, use the command "/gamerule showDeathMessages false"


# this section defines values for when a player reaches the lower threshold for lives
Out-Of-Lives:

  # This section is designated to the configuration of values that are used after someone runs out of lives.

  message: "&c&lYou have run out of lives!"

  # message refers to the message the player will be sent when their lives are out

  command:
      - "say %player% has run out of lives"
  # command refers to a list of console commands that will be run when a player runs out of lives

  force-spectator: true
  # force-spectator refers to if the player will be put into gamemode spectator when they run of out lives
  # Note: It is suggested that the force-spectator be kept to true, unless you want to override it with a command instead, or it is interfering with some aspect of your server

Crafting:

  # This section is designated to the configuration of crafting/recipe values for the plugin.

  enabled: false
  lives: 1
  # determines how many lives the crafted item will give to the player who uses it

  # if you do not wish to not have to type this all out, you can use the command: /lifesteal config

  # for items [anything with "==: org.bukkit.inventory.ItemStack"], https://www.spigotmc.org/wiki/itemstack-serialization/, will show you a little more info on how to format the item
  item:
    ==: org.bukkit.inventory.ItemStack
    type: REDSTONE
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html gives a list of all the items by material type. NOTE: This list may not be 100% accurate, as sometimes bukkit is dumb.
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "§c§lHeart"
      lore:
        - "§cLifesteal Heart"
        - "§7Right click to use"

  shape:
    - " A "
    - "ABA"
    - " C "
  # shape defines the crafting shape. Essentially, anywhere with a space is no item
  # the spaces with a letter will match the items defined later in the config, the letter must match what you set later
  # example: you put " A " on the first row, so it will be [air] [item A] [air]
  # item A will refer to the item below that has A as its key
  # there can only be 3 items in this list, as there are only max 3 rows in crafting, so if you provide a 4th, it will not be counted.

  # again this is a little complicated, but think of it as the slots in the crafting table, so if you put "A  " for the first row, then there will be Item A (see below) in the first slot of the crafting inventory, followed by two empty spaces of air.

  # the items for the recipe are configured below, remember, the key that you give them (ex. A) is what will be in the shape above.
  # You are free to use your own keys, like "O", "E" or "Z", but remember that you need to update these values for the shape with whatever you use here.

  ingredients:
    A: # this is the first item, remember that you can change "A", "B" and "C" to whatever you want ( as long as it is one character ), just remember to change the values in the shape section above
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_BLOCK
    B:
      ==: org.bukkit.inventory.ItemStack
      type: REDSTONE
    C:
      ==: org.bukkit.inventory.ItemStack
      type: GLOWSTONE_DUST

    # you can also add more down here if you wish to have more
    # you can also delete ones, you do not have to have 3, but just make sure you update your shape section :)

  # again, these are the ingredients that will be in the recipe, their key (exmaple: 'A') is what relates to their poisiton in the "shape:" section.

  # the default recipe uses DIAMOND_BLOCK, REDSTONE, GLOWSTONE_DUST
  # it looks like:
  # [AIR] [DIAMOND_BLOCK] [AIR]
  # [DIAMOND_BLOCK] [REDSTONE] [DIAMOND_BLOCK]
  # [AIR] [GLOWSTONE_DUST] [AIR]

  # hopefully this makes sense, if you have trouble, do not feel scared to ask in the Discord server (#support) -> https://x.echology.page/discord

  auto-version: false
  # this will automatically replace your set items with ones up to date with the server version
  # enable this if you wish to use newer items, from versions such as 1.16+
  # NOTE: this will remove all the comments from the config file (besides those at the very top)
