name: Lifesteal
version: 7.0.4
main: page.echology.lifesteal.Lifesteal
api-version: 1.17
author: Echology
website: https://www.echology.page
description: Add combat-based lifesteal to your server! Gain lives by getting kills, lose lives by being killed.